### ISSUE TITLE
[UG] Standardise bullet point style

### ISSUE THREAD

**Issue by aizatazhar** [AY2021S1-CS2103T-W15-4/tp#164]
Not really sure what this is referring to but I presume
![image](https://user-images.githubusercontent.com/39623254/97082699-39e4a000-163e-11eb-9cdf-a7643e11bcf7.png)
the bullet point used here is not the same black one used in the rest??

**Comment by m0nggh** [comment]
I think the white bullet point is because of the further indentation. Not really sure how to solve this.

**Comment by koonweee** [comment]
The bullet points are currently standardized by indentation level, will be kept as it is for now.
