### ISSUE TITLE
[DG] Move lifeline note to the introduction section

### ISSUE THREAD

**Issue by aizatazhar** [AY2021S1-CS2103T-W15-4/tp#209]
It is quite repetitive to see this note on every sequence diagram

 `Note: The lifeline for DeleteCommandParser should end at the destroy marker (X) but due to a limitation of PlantUML, the lifeline reaches the end of diagram. `

**Comment by m0nggh** [comment]
I feel like it is okay to just leave them separately since it is difficult to scroll up to refer to such a note/reminder.
