### ISSUE TITLE
CommandResult when adding/deleting an animal is missing "name" field

### ISSUE THREAD

**Issue by aizatazhar** [AY2021S1-CS2103T-W15-4/tp#232]
`add n/kai kai i/1234 s/Giant Panda` gives

`New animal added: kai kai ID: 1234 Species: Giant Panda Medical conditions:  Feeding times: `

The rest of the fields are displayed as `field: input` except name

**Comment by lamlaaaam** [comment]
I think this was a deliberate action by AB3 since it sounds more direct. You directly list out the (then) person by name, before listing his fields out. But I agree it looks inconsistent and could be seen that way.
