### ISSUE TITLE
Discrepancy in introduction for DG

### ISSUE THREAD

**Issue by m0nggh** [AY2021S1-CS2103T-W15-4/tp#280]
Sorry but I just realised that the introduction format looks alright on the DG file itself but the format seems to be off on the DG website itself.

![image](https://user-images.githubusercontent.com/65110268/97795996-15915080-1c48-11eb-80ac-55cb7ca4913f.png)
In the file, it looks alright.

![image](https://user-images.githubusercontent.com/65110268/97795988-027e8080-1c48-11eb-9355-789cbfe866fc.png)
On the website, it does not but I'm not sure why.

**Comment by aizatazhar** [comment]
It's missing a new line between line 13 and 14
