### ISSUE TITLE
Update constants/variables in tests to reflect animals instead of humans

### ISSUE THREAD

**Issue by aizatazhar** [AY2021S1-CS2103T-W15-4/tp#88]
E.g. in `TypicalAnimals`  we currently have

```
public static final Animal ALICE = new AnimalBuilder().withName("Alice Pauline")
            .withSpecies("123, Jurong West Ave 6, #08-111")
            .withId("94351253")
            .withMedicalConditions("friends").build();
```

**Comment by m0nggh** [comment]
Will look at other files to see if there are necessary changes, thanks!

**Comment by aizatazhar** [comment]
~@m0nggh Sorry could you hold until my PR (#90) is merged so work doesn't get repeated? I have renamed some files but I didn't touch the sample animals (stuff like Bob Alice etc)~

**Comment by lamlaaaam** [comment]
Is this the same issue as #79 ?

**Comment by m0nggh** [comment]
I think they are in different files, I can check all together at once actually.
